[buttons_ru]
yes = 'โ ะะฐ'
no = 'โ ะะตั'
profile = "๐ ะะพะน ะฟัะพัะธะปั"
metodic = "๐ ะะตัะพะดะธัะบะธ"
textbook = "๐ ะฃัะตะฑะฝะธะบ"
shedule = "๐ ะะฐัะฟะธัะฐะฝะธะต ะฟัะตะฟะพะดะฐะฒะฐัะตะปั"
graph_task = 'โ ะกะดะฐัั ะทะฐะดะฐัั'
contact = "๐ ะะพะฝัะฐะบัั ะฟัะตะฟะพะดะฐะฒะฐัะตะปั"
static = "ะกัะฐัะธะบะฐ"
kinematic = "ะะธะฝะตะผะฐัะธะบะฐ"
dynamic = "ะะธะฝะฐะผะธะบะฐ"
shortcourse = 'ะััั ะขะตะพัะผะตั'
vk = 'ะะ'
telegram = 'Telegram'
today = 'ะกะตะณะพะดะฝั'
tomorrow = 'ะะฐะฒััะฐ'
after_tom = 'ะะพัะปะตะทะฐะฒััะฐ'
to_2_day = 'ะงะตัะตะท 2 ะดะฝั'
all = 'ะัะต'
mailer = 'โ ะะฐัััะปะบะฐ'
question = 'โ ะะพะฟัะพั ะฟัะตะฟะพะดะฐะฒะฐัะตะปั'
send = 'ะัะฒะตัะธัั'
